-- Create a table to store levels generated by instructors or AI
CREATE TABLE IF NOT EXISTS public.course_levels (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    course_id VARCHAR(50) NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
    level_order INTEGER NOT NULL, -- The order of the level (1, 2, 3...)
    name VARCHAR(255) NOT NULL,
    description TEXT,
    initial_code TEXT,
    expected_output TEXT,
    solution TEXT,
    hints JSONB DEFAULT '[]'::jsonb,
    rewards JSONB DEFAULT '{"exp": 100, "coins": 50}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(course_id, level_order) -- Ensure unique level number per course
);

-- RLS Policies
ALTER TABLE public.course_levels ENABLE ROW LEVEL SECURITY;

-- Everyone can read levels (for gameplay)
CREATE POLICY "Anyone can read course levels" ON public.course_levels 
    FOR SELECT USING (true);

-- Instructors and Admins can insert/update/delete
CREATE POLICY "Instructors can manage levels" ON public.course_levels 
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.users 
            WHERE users.id = auth.uid() 
            AND users.role IN ('instructor', 'admin')
        )
    );
